//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faq()
        {
            this.Tiquetes = new HashSet<Tiquete>();
        }
    
        public int IdFaq { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Solucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiquete> Tiquetes { get; set; }
    }
}
