//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int IdMensaje { get; set; }
        public string Mensaje1 { get; set; }
        public System.DateTime MensjFecha { get; set; }
        public int IdTiquete { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    }
}
